# Generated by Django 4.2.6 on 2023-10-29 01:27

from django.db import migrations, models
import django.db.models.deletion
import sheet_api.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Composer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("born_year", models.IntegerField()),
                ("died_year", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ComposerWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "composer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sheet_api.composer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_title", models.CharField(max_length=200)),
                ("composition_year", models.IntegerField()),
                ("opus", models.CharField(max_length=200)),
                ("opus_number", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (sheet_api.models.PuzzleTypes["Piano"], "Piano"),
                            (sheet_api.models.PuzzleTypes["Violin"], "Violin"),
                            (sheet_api.models.PuzzleTypes["Cello"], "Cello"),
                            (sheet_api.models.PuzzleTypes["Orchestral"], "Orchestral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("sheet_image_url", models.CharField(max_length=200)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sheet_api.composerwork",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="composerwork",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sheet_api.work"
            ),
        ),
    ]
