# Generated by Django 4.2.6 on 2023-12-31 03:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sheet_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="composer",
            name="first_scanned",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="composer",
            name="last_scanned",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="work",
            name="composer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="sheet_api.composer",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="first_scanned",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="work",
            name="last_scanned",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sheet_api.work"
            ),
        ),
        migrations.DeleteModel(
            name="ComposerWork",
        ),
    ]
