# Generated by Django 4.2.6 on 2024-01-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet_api", "0003_composer_unique_full_name_first_name_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composer",
            name="born_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
