# Generated by Django 4.2.6 on 2024-01-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet_api", "0004_alter_composer_born_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="type",
            field=models.CharField(
                choices=[
                    ("P", "Piano"),
                    ("V", "Violin"),
                    ("C", "Cello"),
                    ("O", "Orchestral"),
                ],
                max_length=5,
            ),
        ),
    ]
