# Generated by Django 4.2.6 on 2024-01-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet_api", "0005_alter_puzzle_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="puzzle",
            constraint=models.UniqueConstraint(
                fields=("type", "date"), name="unique_type_date"
            ),
        ),
    ]
