# Generated by Django 4.2.6 on 2024-02-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet_api", "0006_puzzle_unique_type_date"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="puzzle",
            index=models.Index(
                fields=["type", "date"], name="sheet_api_p_type_e78e00_idx"
            ),
        ),
    ]
