# Generated by Django 4.2.6 on 2024-02-24 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sheet_api", "0007_puzzle_sheet_api_p_type_e78e00_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("GUESS_MADE", "Guess made"),
                            ("PUZZLE_VIEWED", "Puzzle viewed"),
                            ("PUZZLE_SOLVED", "Puzzle solved"),
                            ("PUZZLE_FAILED", "Puzzle failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_body", models.JSONField(max_length=1000)),
                ("event_time", models.DateTimeField(auto_now_add=True)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sheet_api.puzzle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event_type"], name="sheet_api_u_event_t_8031cc_idx"
                    ),
                    models.Index(
                        fields=["puzzle"], name="sheet_api_u_puzzle__076ea3_idx"
                    ),
                ],
            },
        ),
    ]
