# Generated by Django 4.2.6 on 2024-02-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet_api", "0008_usageevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageevent",
            name="session_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
