# Generated by Django 4.2.6 on 2024-02-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet_api", "0009_usageevent_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="composer",
            name="catalog_prefix",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
