# Generated by Django 4.2.6 on 2024-07-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheet_api", "0010_composer_catalog_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="difficulty",
            field=models.IntegerField(
                choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")], default=2
            ),
        ),
    ]
